version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-intuitive
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intuitive_teste
    ports:
      - "3306:3306"